import ogImageSrc from "@images/favico.png";

export const SITE = {
  title: "Sinergia Valores S.A",
  tagline: "El puente hacia tu nuevo hogar Sinergia Valores.",
  description:
    "Garantiza tu futuro hogar en segundos - Solicita una fianza con nosotros.",
  description_short: "Garantiza tu futuro hogar en segundos.",
  url: "https://www.sinergiavalores.com",
  author: "Alvaro Goncalves Y Nico De Caroli :)",
};

export const SEO = {
  title: SITE.title,
  description: SITE.description,
  structuredData: {
    "@context": "https://schema.org",
    "@type": "WebPage",
    inLanguage: "es-AR",
    "@id": SITE.url,
    url: SITE.url,
    name: SITE.title,
    description: SITE.description,
    isPartOf: {
      "@type": "WebSite",
      url: SITE.url,
      name: SITE.title,
      description: SITE.description,
    },
  },
};

export const ArrepentimientoFormInfo = {
  title: "Arrepentimiento",
  description:
    "Solicitar la revocación de un producto o servicio contratado con Sinergia Valores S.A. dentro de los 10 (diez) días corridos contados a partir de la fecha de recibido el contrato o de la disponibilidad efectiva del producto o servicio, lo que suceda último; de esta manera, podrás arrepentirte y deshacer la contratación del producto/servicio solicitado en ese plazo informado.",
  name: "Nombre Completo",
  // lastname: "Apellido",
  nacionality: "Nacionalidad",
  idnumber: "Documento y Numero",
  phonenumber: "Telefono/Celular de contacto",
  mail: "Mail",
  serviceorproduct: "Servicio o Producto",
  sendtext: "Enviar",
};

// Clase compartida por los links que aparecen dentro de las respuestas de los FAQ.
const faqLink =
  "font-gotham text-neutral-800 underline underline-offset-2 hover:text-neutral-500 dark:text-neutral-200 dark:hover:text-neutral-400";

const WHATSAPP_URL =
  "https://wa.me/5492216145726?text=Hola%2C%20me%20estoy%20comunicando%20del%20sitio%20web%20de%20Sinergia%20Valores%20para%20hacer%20una%20consulta.";

export const questionsFrecuentes = [
  {
    category: "General",
    faqs: [
      {
        question: "¿QUIENES SOMOS?",
        answer:
          "EQUIPO DE PROFESIONALES DEDICADOS A LA GESTIÓN DE SERVICIOS FINANCIEROS.",
      },
      {
        question: "¿QUE ES LA GARANTÍA PARA ALQUILER DE SINERGIA?",
        answer:
          "ES UNA FIANZA PRIVADA 100% QUE SURGE DEL ANÁLISIS SOBRE LA CAPACIDAD ECONÓMICA DEL INQUILINO, QUE SE CARACTERIZA POR LA CELERIDAD EN EL CIERRE DEL CONTRATO DE ALQUILER PARA EL INQUILINO Y EN LA LIQUIDEZ INMEDIATA PARA EL PROPIETARIO.",
      },
      {
        question:
          "¿CUAL ES LA DIFERENCIA ENTRE LA GARANTÍA DE ALQUILER Y LA GARANTÍA PROPIETARIA?",
        answer:
          "LA DIFERENCIA PRINCIPAL ES LA AUTONOMÍA, YA QUE NO NECESITAS PEDIRLE FAVORES A NADIE NI COMPROMETER EL PATRIMONIO DE UN FAMILIAR. EVALUAMOS TU CAPACIDAD DE PAGO Y SI SOS UN BUEN PERFIL, TENES TU GARANTÍA EN 24 HS.",
      },
      {
        question: "¿QUÉ TIPO DE CONTRATOS DE ALQUILER CUBRE SINERGIA?",
        answer:
          "SE BRINDA COBERTURA SOBRE CONTRATOS DE ALQUILER DE TIPO RESIDENCIAL Y COMERCIAL. EN EL CASO DE ALQUILERES RESIDENCIALES LA GARANTÍA CUBRE EL ALQUILER, EXPENSAS ORDINARIAS, SERVICIOS (DETALLADOS EN EL CONTRATO DE ALQUILER A NOMBRE DEL INQUILINO) Y LOS GASTOS EXTRAJUDICIALES Y JUDICIALES HASTA LA RESTITUCIÓN DE LA PROPIEDAD. EN EL CASO DE CONTRATOS COMERCIALES OFRECEMOS GARANTÍAS ADAPTADAS A LAS NECESIDADES DE PYMES, PROFESIONALES Y EMPRENDEDORES.",
      },
      {
        question: "¿TIENE RESPALDO LEGAL LA GARANTÍA DE SINERGIA?",
        answer:
          "EN PRIMER LUGAR, LA GARANTÍA TIENE PLENA VALIDEZ DENTRO DEL MARCO NORMATIVO ARGENTINO EN EL ARTÍCULO 1.187 Y SIGUIENTES DEL C.C.C.N, ANTE LA DEROGACIÓN DE LA LEY DE ALQUILERES POR MEDIO DEL DNU 70/2023. A SU VEZ, LA GARANTÍA ES EMITIDA DIGITALMENTE CON CERTIFICACIÓN NOTARIAL LO QUE LE OTORGA FUERZA PROBATORIA Y RECONOCIMIENTO LEGAL ANTE UNA EVENTUALIDAD JUDICIAL.",
      },
      {
        question: "¿MIS DATOS ESTÁN PROTEGIDOS?",
        answer:
          "LA INFORMACIÓN INGRESADA POR LOS USUARIOS ES TRATADA DE FORMA CONFIDENCIAL BAJO UN ESTRICTO PROTOCOLO DE SEGURIDAD, RESPETANDO LA NORMATIVA VIGENTE DE ACUERDO CON LA LEY DE PROTECCIÓN DE DATOS PERSONALES N° 25.326 Y DEMÁS NORMATIVA APLICABLE EN ARGENTINA.",
      },
      {
        question: "¿CÓMO BRINDAMOS SOPORTE?",
        answer: `NUESTRO EQUIPO ESTÁ DISPONIBLE DESDE LA PRE-APROBACIÓN DE LA GARANTÍA DE ALQUILER HASTA LA RESTITUCIÓN DE LA PROPIEDAD MEDIANTE CANALES PRESENCIALES CON SEDE EN LA CIUDAD DE LA PLATA COMO MEDIANTE CONTACTO POR <a target="_blank" rel="noopener noreferrer" class="${faqLink}" href="${WHATSAPP_URL}">WHATSAPP</a> TANTO PARA EL INQUILINO, COMO PARA LA INMOBILIARIA Y EL PROPIETARIO. NUESTRO OBJETIVO ES EL ESTRICTO CUMPLIMIENTO DEL CONTRATO LOCATIVO Y EL ACOMPAÑAMIENTO DEL INQUILINO EN TODO EL PROCESO.`,
      },
      {
        question: "¿OFRECEN ATENCIÓN PERSONALIZADA?",
        answer:
          "ENTENDEMOS QUE EL MERCADO NO ESPERA. POR ESO COMBINAMOS EL TRATO HUMANO DE NUESTROS ASESORES CON LA RAPIDEZ DE NUESTRA TECNOLOGÍA, DÁNDOTE RESPUESTA EN MINUTOS.",
      },
      {
        question: "¿TENES ALGUNA DUDA?",
        answer: `<a target="_blank" rel="noopener noreferrer" class="${faqLink}" href="${WHATSAPP_URL}">COMUNICATE CON NOSOTROS POR WHATSAPP</a>.`,
      },
    ],
  },
  {
    category: "Inquilinos",
    faqs: [
      {
        question:
          "¿QUÉ DOCUMENTACIÓN ES NECESARIA PARA APLICAR EN EL SISTEMA DE GARANTÍAS DE ALQUILER DE SINERGIA?",
        answer: `LA DOCUMENTACIÓN OBLIGATORIA SE ENCUENTRA EN LA PÁGINA WEB EN LA OPCIÓN DE <a href="/files/REQUISITOS.pdf" target="_blank" rel="noopener noreferrer" class="${faqLink}">REQUISITOS</a>.`,
      },
      {
        question:
          "¿SI NO TENGO INGRESOS EN RELACIÓN DE DEPENDENCIA O FACTURACIÓN PUEDO APLICAR AL SISTEMA DE GARANTÍAS DE ALQUILER?",
        answer: `EN TAL CASO <a target="_blank" rel="noopener noreferrer" class="${faqLink}" href="${WHATSAPP_URL}">ENVIANOS LA CONSULTA</a> Y TE ENVIAREMOS ALTERNATIVAS PERSONALIZADAS EN EL DÍA.`,
      },
      {
        question:
          "¿SI SOY EXTRANJERO PUEDO APLICAR AL SISTEMA DE GARANTÍA PARA ALQUILER?",
        answer: `EN TAL CASO <a target="_blank" rel="noopener noreferrer" class="${faqLink}" href="${WHATSAPP_URL}">ENVIANOS LA CONSULTA</a> Y TE ENVIAREMOS ALTERNATIVAS PERSONALIZADAS EN EL DÍA.`,
      },
      {
        question:
          "¿SI TENGO INGRESOS EN EL EXTERIOR PUEDO CALIFICAR PARA EL SISTEMA DE GARANTÍAS DE ALQUILER?",
        answer: `EN TAL CASO <a target="_blank" rel="noopener noreferrer" class="${faqLink}" href="${WHATSAPP_URL}">ENVIANOS LA CONSULTA</a> Y TE ENVIAREMOS ALTERNATIVAS PERSONALIZADAS EN EL DÍA.`,
      },
      {
        question:
          "¿LA GARANTÍA DE SINERGIA VARÍA EN BASE AL AJUSTE DEL ALQUILER?",
        answer:
          "NO, LA GARANTÍA SE CONTRATA POR UN VALOR FIJO AL MOMENTO DE LA EMISIÓN.",
      },
      {
        question:
          "¿ES POSIBLE ACTUALIZAR LOS DATOS PERSONALES ESTANDO LA GARANTÍA ACTIVA?",
        answer:
          "SI, ES NECESARIO TOMAR CONTACTO CON EL EQUIPO ADMINISTRATIVO DE SINERGIA MEDIANTE LOS CANALES DE CONTACTO OFICIALES.",
      },
      {
        question:
          "¿SI LA EMPRESA ES NUEVA PUEDO APLICAR PARA EL SISTEMA DE GARANTÍAS DE ALQUILER?",
        answer: `EN TAL CASO <a target="_blank" rel="noopener noreferrer" class="${faqLink}" href="${WHATSAPP_URL}">ENVIANOS LA CONSULTA</a> Y TE ENVIAREMOS ALTERNATIVAS PERSONALIZADAS.`,
      },
      {
        question: "¿ES POSIBLE TRANSFERIR LA GARANTÍA A OTRO CONTRATO?",
        answer:
          "NO, DADO QUE CADA CONTRATO DE ALQUILER ES ÚNICO Y LA GARANTÍA ES ESPECÍFICA. PERO NO TE PREOCUPES, SI TE MUDÁS, PODÉS USAR TU CERTIFICADO DE CUMPLIMIENTO ÓPTIMO PARA OBTENER MEJORES CONDICIONES EN TU PRÓXIMO TRÁMITE CON NOSOTROS.",
      },
      {
        question:
          "¿SI SOY MONOTRIBUTISTA CALIFICO PARA EL SISTEMA DE GARANTÍAS DE ALQUILER?",
        answer: `SI, PRESENTANDO LA <a href="/files/REQUISITOS.pdf" target="_blank" rel="noopener noreferrer" class="${faqLink}">DOCUMENTACIÓN REQUERIDA</a> OBTENES TU CALIFICACIÓN EN 24 HS.`,
      },
      {
        question: "¿QUÉ ES UN CO-GARANTE?",
        answer:
          "ES UN APOYO FINANCIERO PARA TU APLICACIÓN, CON SINERGIA TU ERES EL TITULAR Y PROTAGONISTA DE TU PROPIO CONTRATO DE ALQUILER.",
      },
      {
        question:
          "¿QUÉ SUCEDE SI LA GARANTÍA ES ABONADA, PERO LA OPERACIÓN INMOBILIARIA ES CANCELADA?",
        answer:
          "EN TAL CASO SE PROCEDE A RESTITUIR EL VALOR ABONADO POR EL CLIENTE SIN NINGÚN TIPO DE DESCUENTO.",
      },
      {
        question: "¿QUÉ NECESITO PARA COTIZAR EL SERVICIO?",
        answer: `ES POSIBLE MEDIANTE LA <a href="/calculadora" class="${faqLink}">CALCULADORA INTEGRADA</a> TENER UN PRESUPUESTO APROXIMADO. EL PRESUPUESTO FINAL SE CONCLUYE EN BASE A LOS VALORES REALES DEL CONTRATO DE ALQUILER Y LA DOCUMENTACIÓN REQUERIDA.`,
      },
      {
        question: "¿QUÉ ES EL PROGRAMA DE CUMPLIMIENTO ÓPTIMO DE SINERGIA?",
        answer:
          "SI AL FINALIZAR TU CONTRATO NO TUVISTE NINGÚN RETRASO CON EL PAGO DEL ALQUILER, EXPENSAS Y SERVICIOS TE DEVOLVEMOS 10 % DE LA PRIMA QUE PAGASTE. A SU VEZ TE ENVIAMOS POR MAIL UN CERTIFICADO DE CUMPLIMIENTO ÓPTIMO CON EL CUAL RECIBIRÁS UN SERVICIO MÁS RÁPIDO Y EFICIENTE CON TU PRÓXIMA RENOVACIÓN.",
      },
      {
        question: "¿CUÁNDO ME ENVÍAN EL CERTIFICADO DE CUMPLIMIENTO ÓPTIMO?",
        answer:
          "SE ENVÍA LUEGO DE FINALIZADO EL PLAZO LOCATIVO. EL CERTIFICADO ES VERIFICABLE EN NUESTRA PÁGINA MEDIANTE QR, Y PERMITE TENER TRAZABILIDAD ANTE CUALQUIER CONSULTA MEDIANTE TU HISTORIAL CON NOSOTROS.",
      },
      {
        question: "¿CÓMO SE ABONA EL SERVICIO?",
        answer:
          "SE ABONA MEDIANTE PAGO DE CONTADO, DEPÓSITO O TRANSFERENCIA BANCARIA. EN CASO DE REQUERIR ALTERNATIVAS EN CUOTAS, SINERGIA DISPONE DE ALTERNATIVAS DE PAGO SIN INTERÉS.",
      },
      {
        question: "¿QUE ES EL PROGRAMA POR RENOVACIÓN?",
        answer:
          "SI AL FINALIZAR EL CONTRATO NECESITAS GESTIONAR UNA RENOVACIÓN DE LA GARANTÍA DE ALQUILER, OBTENES UN 20% DE DESCUENTO SOBRE EL PRÓXIMO CONTRATO DE FIANZA. EL MISMO DESCUENTO NO ES ACUMULATIVO CON EL DESCUENTO POR PAGO DE CONTADO, SINO QUE PASA A REEMPLAZARLO SEA CUAL FUESE EL FORMATO DE PAGO QUE DECIDAS.",
      },
      {
        question: "¿PUEDO SABER SI CALIFICO ANTES DE ELEGIR LA PROPIEDAD?",
        answer: `CLARO, NO NECESITAS PERDER EL TIEMPO, <a href="/#calculadora" class="${faqLink}">COTIZÁ EN 30 SEGUNDOS DE MANERA GRATUITA</a> Y LUEGO OBTENÉ TU <a href="/solicitud" class="${faqLink}">PRE-APROBACIÓN</a>.`,
      },
      {
        question: "¿CUÁNTO TIEMPO TARDA EN APROBARSE LA GARANTÍA DE ALQUILER?",
        answer:
          "EL INQUILINO TIENE PRE-APROBACIÓN INMEDIATA Y EN 24 HS HÁBILES A PARTIR DE LA RECEPCIÓN DE LA DOCUMENTACIÓN COMPLETA TIENE LA APROBACIÓN FINAL.",
      },
      {
        question: "¿ES POSIBLE COORDINAR UNA REUNIÓN?",
        answer:
          "SI, COORDINAMOS UNA REUNIÓN PRESENCIAL O VÍA ZOOM. EN CASO DE SER PRESENCIAL, ES POSIBLE COORDINARLAS EN NUESTRAS OFICINAS CON SEDE EN LA PLATA.",
      },
      {
        question:
          "¿NECESITO TENER UNA PROPIEDAD DEFINIDA PARA COTIZAR EL SERVICIO?",
        answer: `NO ES NECESARIO, MEDIANTE LA <a href="/#calculadora" class="${faqLink}">CALCULADORA INTEGRADA</a> ES POSIBLE COTIZAR DE MANERA GRATUITA Y 100 % ONLINE INDICANDO EL MONTO DE ALQUILER Y EXPENSAS.`,
      },
      {
        question: "¿TENGO UN CERTIFICADO DE RESPALDO?",
        answer:
          "SI, TE ENVIAMOS UN CERTIFICADO DE PRE-APROBACIÓN AL MAIL CON FIRMA DIGITAL DE SINERGIA, PARA QUE LO PRESENTES EN LA INMOBILIARIA Y PUEDAS CERRAR EL CONTRATO CON SEGURIDAD.",
      },
      {
        question: "¿QUÉ PASA SI LA INMOBILIARIA NO CONOCE A SINERGIA?",
        answer:
          "¡NOSOTROS NOS OCUPAMOS! CONTACTAMOS A TU INMOBILIARIA Y LE EXPLICAMOS EL SERVICIO.",
      },
    ],
  },
  {
    category: "Propietario",
    faqs: [
      {
        question:
          "¿CÓMO SE GESTIONA EL RECLAMO ANTE INCUMPLIMIENTO POR PARTE DEL INQUILINO?",
        answer: `LA GESTIÓN DEL RECLAMO SE REALIZA POR MEDIO DE LA SECCIÓN DE <a href="/incumplimiento" class="${faqLink}">INCUMPLIMIENTO</a> DENTRO DE LA PÁGINA WEB.`,
      },
      {
        question: "¿CÓMO ACTUAMOS ANTE UNA SITUACIÓN DE MORA?",
        answer:
          "NUESTRO OBJETIVO ES LA EFECTIVIDAD DEL CONTRATO. ANTE UN INCUMPLIMIENTO, INICIAMOS UN PROTOCOLO DE GESTIÓN PROFESIONAL PARA LOGRAR UNA RESOLUCIÓN EXTRAJUDICIAL ÁGIL, RESGUARDANDO TU RENTABILIDAD Y EVITANDO BUROCRACIAS JUDICIALES INNECESARIAS.",
      },
      {
        question:
          "¿TIENE EL PROPIETARIO GASTOS JUDICIALES O EXTRAJUDICIALES EN CASO DE INCUMPLIMIENTO?",
        answer:
          "NO, LOS GASTOS JUDICIALES Y EXTRAJUDICIALES ESTÁN GARANTIZADOS EN EL CONTRATO DE GARANTÍA HASTA LA RESTITUCIÓN DEL BIEN.",
      },
      {
        question:
          "¿TIENE EL PROPIETARIO GASTOS POR LA GESTIÓN DE LA GARANTÍA DE ALQUILER?",
        answer: "NO, ES UN GASTO DEL INQUILINO.",
      },
      {
        question:
          "¿QUÉ COBERTURA Y PLAZO TIENE LA GARANTÍA DE ALQUILER DE SINERGIA?",
        answer: `LA GARANTÍA CUBRE ALQUILER, EXPENSAS ORDINARIAS Y SERVICIOS DETALLADOS EN EL CONTRATO DE GARANTÍA HASTA LA RESTITUCIÓN DEL BIEN. EN LA PÁGINA WEB SE ENCUENTRA EL <a href="/files/Contrato.pdf" target="_blank" rel="noopener noreferrer" class="${faqLink}">CONTRATO DE ADHESIÓN AL SERVICIO</a>, EN EL CUAL SE DETALLA DE MANERA TRANSPARENTE TANTO EL PLAZO COMO LA COBERTURA DE LA GARANTÍA. A SU VEZ, MEDIANTE LOS CANALES OFICIALES DE SINERGIA VALORES ES POSIBLE COMUNICARSE Y RECIBIR EL ASESORAMIENTO QUE SE REQUIERA.`,
      },
      {
        question: "¿COMO SÉ SI EL INQUILINO CUENTA CON LA GARANTÍA DE SINERGIA?",
        answer:
          "CUANDO EL INQUILINO PRECALIFICA PARA LA GARANTÍA DE SINERGIA, SE LE ENVÍA EL CERTIFICADO DE PRE-APROBACIÓN POR MAIL CON FIRMA DIGITAL CONFIRMANDO QUE CUMPLE CON LOS REQUISITOS NECESARIOS PARA OBTENER LA GARANTÍA. EN CASO DE APLICAR, PREVIO A LA FIRMA DEL CONTRATO DE ALQUILER, SE PROCEDE A VALIDAR LA INFORMACIÓN DEL INQUILINO, LOCADOR Y PROPIEDAD EN CONJUNTO CON LA INMOBILIARIA. LUEGO DE VALIDAR LA INFORMACIÓN SE PROCEDE AL ENVÍO DEL CONTRATO DE GARANTÍA CON CERTIFICACIÓN NOTARIAL DIGITAL AL INQUILINO, LOCADOR E INMOBILIARIA.",
      },
      {
        question: "¿HASTA DÓNDE LLEGA NUESTRA COBERTURA?",
        answer:
          "EL RESPALDO DE SINERGIA TRASCIENDE EL SIMPLE ABONO LOCATIVO. BRINDAMOS PROTECCIÓN JURÍDICA Y UN SEGUIMIENTO INTEGRAL EN CADA ETAPA, ASEGURANDO TU RENTABILIDAD HASTA LA EFECTIVA RESTITUCIÓN DEL BIEN. SOMOS TU TRANQUILIDAD DE PRINCIPIO A FIN.",
      },
      {
        question: "¿CUÁNDO RECIBO LA GARANTÍA DE SINERGIA?",
        answer:
          "LUEGO DE FINALIZADO EL PROCESO DE PRE-APROBACIÓN DEL INQUILINO Y HABIENDO VALIDADO LA INFORMACIÓN DEL LOCADOR Y LA PROPIEDAD EN CONJUNTO CON LA INMOBILIARIA, SE PROCEDE AL ENVÍO DEL CONTRATO DE GARANTÍA CON CERTIFICACIÓN NOTARIAL DIGITAL AL INQUILINO, LOCADOR E INMOBILIARIA. DE ESTA MANERA DISPONES DEL CONTRATO DE GARANTÍA CON VALIDEZ LEGAL PREVIO A LA FIRMA DEL CONTRATO DE ALQUILER. MEDIANTE LA VALIDACIÓN DE LA PROPIEDAD Y EL CONTRATO, NO SOLO ASEGURAMOS EL CUMPLIMIENTO DEL PAGO, SINO QUE TAMBIÉN VERIFICAMOS LA CORRECTA INSTRUMENTACIÓN DEL CONTRATO, OTORGÁNDOLE UNA PROTECCIÓN JURÍDICA INTEGRAL.",
      },
      {
        question: "¿ES POSIBLE COORDINAR UNA REUNIÓN?",
        answer:
          "SI, COORDINAMOS UNA REUNIÓN PRESENCIAL O VÍA ZOOM. EN CASO DE SER PRESENCIAL, ES POSIBLE COORDINARLAS EN NUESTRAS OFICINAS.",
      },
      {
        question:
          "¿COMO PUEDO VERIFICAR QUE LA GARANTÍA DE ALQUILER ES VÁLIDA?",
        answer: `EL <a href="/files/Contrato.pdf" target="_blank" rel="noopener noreferrer" class="${faqLink}">CONTRATO DE ADHESIÓN AL SERVICIO</a> TIENE CERTIFICACIÓN NOTARIAL DIGITAL.`,
      },
      {
        question:
          "¿SE REQUIERE LA FIRMA DEL PROPIETARIO EN ALGÚN DOCUMENTO ADICIONAL?",
        answer:
          "NO ES NECESARIO QUE EL LOCADOR FIRME DOCUMENTACIÓN ADICIONAL, DADO QUE EL CONTRATO DE GARANTÍA QUEDA FORMALMENTE VALIDADO MEDIANTE LA CERTIFICACIÓN NOTARIAL DIGITAL. SOLO EN EL CASO DE UN SEGUNDO INCUMPLIMIENTO POR PARTE DEL INQUILINO, SE LE REQUERIRÁ AL PROPIETARIO UN PODER ESPECIAL PARA INICIAR ACCIONES JUDICIALES POR PARTE DE SINERGIA VALORES.",
      },
      {
        question:
          "¿POR QUÉ ES MEJOR SINERGIA VALORES QUE UNA GARANTÍA PROPIETARIA TRADICIONAL?",
        answer:
          "PORQUE CON NOSOTROS EL PROPIETARIO NO TIENE QUE INVESTIGAR SI LA PROPIEDAD DE GARANTÍA ES REAL, SI ESTÁ EMBARGADA O SI LOS FIRMANTES PUEDEN SER GARANTES. NOSOTROS GESTIONAMOS ESE ANÁLISIS GARANTIZANDO QUE EL RESPALDO SEA REAL, LÍQUIDO Y EJECUTABLE AL INSTANTE.",
      },
    ],
  },
  {
    category: "Inmobiliaria",
    faqs: [
      {
        question:
          "¿QUÉ VENTAJAS TIENE FORMAR PARTE DE LA RED DE INMOBILIARIAS ADHERIDAS DE SINERGIA?",
        answer:
          "EN PRIMER LUGAR, LOS INMUEBLES EN ALQUILER SON PUBLICADOS EN NUESTRA PÁGINA Y REDES SOCIALES. EN SEGUNDO LUGAR, ESTAMOS PRESENTES POR MEDIOS PUBLICITARIOS, Y FORMARÁN PARTE DE NUESTROS ANUNCIOS. POR ÚLTIMO, LA INMOBILIARIA QUE SE ADHIERA AL SISTEMA DE GARANTÍAS PARA ALQUILER DE SINERGIA VALORES, FORMA PARTE DEL PROGRAMA DE COMISIONES POR VOLUMEN DE CONTRATOS CONCERTADOS Y PROGRAMAS DE FIDELIZACIÓN.",
      },
      {
        question: "¿CÓMO AGILIZAMOS EL CIERRE DE TUS NEGOCIOS?",
        answer:
          "MINIMIZAMOS EL RIESGO DE PÉRDIDA EN LAS OPERACIONES. ANTE LA AUSENCIA DE RESPALDO PROPIETARIO, EVITAMOS QUE SE FRUSTRE LA GESTIÓN: SINERGIA VALORES TRANSFORMA AL POSTULANTE EN UN VÍNCULO CONTRACTUAL EFECTIVO EN SOLO 24 HS, POTENCIANDO TU PRODUCTIVIDAD SIN BUROCRACIA.",
      },
      {
        question: "¿CUÁLES SON LOS BENEFICIOS DE ELEGIR LA GARANTÍA DE SINERGIA?",
        answer:
          "NUESTRO SISTEMA SE DESTACA POR LA EXHAUSTIVA EVALUACIÓN DE LOS PERFILES Y LA CELERIDAD EN LA RESPUESTA. GRACIAS A NUESTRA SOLVENCIA, TU IMAGEN FRENTE AL LOCADOR PERMANECE PROTEGIDA Y SIN RIESGOS.",
      },
      {
        question: "¿ES POSIBLE COORDINAR UNA REUNIÓN?",
        answer:
          "SI, COORDINAMOS UNA REUNIÓN PRESENCIAL O VÍA ZOOM. EN CASO DE SER PRESENCIAL, ES POSIBLE COORDINARLAS EN LA INMOBILIARIA O EN NUESTRAS OFICINAS.",
      },
      {
        question: "¿ES NECESARIO MODIFICAR MIS CONTRATOS?",
        answer:
          "NO ES NECESARIO. TU OPERATORIA SIGUE SIENDO LA MISMA. ÚNICAMENTE SE SUMA UNA CLÁUSULA ANEXO COMPLEMENTARIA QUE VINCULA NUESTRO RESPALDO. ES UN PROCESO ÁGIL, SENCILLO Y CON TOTAL RESPALDO JURÍDICO.",
      },
      {
        question:
          "¿QUÉ CANALES DE COMUNICACIÓN TENEMOS ANTE UNA CONSULTA TÉCNICA?",
        answer: `CONTAMOS CON CANALES DE COMUNICACIÓN VÍA TELEFÓNICA, MAIL INSTITUCIONAL, <a href="/contacto" class="${faqLink}">PÁGINA WEB</a> Y OFICINAS.`,
      },
      {
        question:
          "¿NUESTRO SISTEMA AFECTA EL COBRO DE TUS HONORARIOS INMOBILIARIOS?",
        answer:
          "DE NINGUNA MANERA. SINERGIA ACTÚA COMO EL RESPALDO DEL CONTRATO, POR LO QUE TU COMISIÓN SE MANTIENE INDEPENDIENTE Y BAJO TU GESTIÓN HABITUAL. AL ACELERAR LA VALIDACIÓN DEL POSTULANTE, LOGRAS QUE LA OPERACIÓN SE CONCRETE CON MAYOR CELERIDAD Y ASÍ PERCIBIR TUS HONORARIOS SIN DEMORAS.",
      },
      {
        question:
          "¿DEBE COORDINAR LA FIRMA DEL CONTRATO DE LOCACIÓN CON SINERGIA?",
        answer:
          "NO, LA FIRMA DEL CONTRATO DE LOCACIÓN ES RESPONSABILIDAD DE LA INMOBILIARIA. DESDE SINERGIA VALORES ENVIAMOS EL CONTRATO DE GARANTÍA DE ALQUILER CON CERTIFICACIÓN NOTARIAL DIGITAL POR MAIL AL INQUILINO, PROPIETARIO E INMOBILIARIA PREVIO A LA FIRMA DEL CONTRATO DE LOCACIÓN.",
      },
    ],
  },
  {
    category: "Alquileres comerciales",
    faqs: [
      {
        question:
          "¿OFRECEN GARANTÍAS PARA ALQUILER PARA LOCALES COMERCIALES, OFICINAS O DEPÓSITOS?",
        answer:
          "SI, EN SINERGIA VALORES OFRECEMOS GARANTÍAS DE ALQUILER PARA LOCALES, DEPÓSITOS, CONSULTORIOS Y CUALQUIER INMUEBLE DESTINADO A DESTINO COMERCIAL.",
      },
      {
        question: "¿QUÉ REQUISITOS NECESITO PARA ALQUILAR UN DESTINO COMERCIAL?",
        answer: `EN <a href="/files/REQUISITOS.pdf" target="_blank" rel="noopener noreferrer" class="${faqLink}">REQUISITOS</a> ESTÁN LOS REQUISITOS NECESARIOS PARA PERSONA FÍSICA Y PARA PERSONA JURÍDICA.`,
      },
      {
        question:
          "¿PUEDO APLICAR PARA LA GARANTÍA DE ALQUILER SI LA EMPRESA ES NUEVA O ESTÁ EN FORMACIÓN?",
        answer:
          "LA FALTA DE ANTIGÜEDAD NO ES UN IMPEDIMENTO PARA TU CRECIMIENTO. ANALIZAMOS TU PROYECTO COMERCIAL Y CAPACIDAD FINANCIERA PARA BRINDARTE RESPUESTAS PERSONALIZADAS QUE SE ADAPTEN A TUS NECESIDADES.",
      },
      {
        question:
          "¿PUEDO SOLICITAR UNA GARANTÍA COMO PROFESIONAL INDEPENDIENTE?",
        answer:
          "EN SINERGIA COMPRENDEMOS QUE LOS INGRESOS DE LOS PROFESIONALES INDEPENDIENTES PUEDEN VARIAR. PRESENTANDO TU CONSTANCIA DE MONOTRIBUTO O DDJJ DE GANANCIAS, EFECTUAMOS UN ANÁLISIS PERSONALIZADO PARA QUE CONSIGAS TU RESPALDO CON CELERIDAD Y PUEDAS CONCRETAR EL ALQUILER DE TU PRÓXIMA OFICINA O LOCAL.",
      },
      {
        question:
          "¿ES NECESARIO QUE EN EL CONTRATO DE ALQUILER SE ESPECIFIQUE EL USO COMERCIAL DEL INMUEBLE?",
        answer:
          "PARA QUE EL RESPALDO TENGA PLENA VALIDEZ Y SE AJUSTE AL MARCO NORMATIVO, ES CONDICIÓN QUE EL VÍNCULO LOCATIVO DETALLE EL USO COMERCIAL. DICHA ESPECIFICACIÓN RESGUARDA EL PATRIMONIO DE LAS PARTES Y ES UN PASO QUE NUESTROS PROFESIONALES VERIFICAN DURANTE LA EMISIÓN PARA GARANTIZAR TU TRANQUILIDAD JURÍDICA INTEGRAL.",
      },
      {
        question: "¿CUÁL ES EL PLAZO PARA LA CALIFICACIÓN COMERCIAL?",
        answer:
          "ENTENDEMOS QUE LAS OPORTUNIDADES DE NEGOCIO NO DEBEN DILATARSE EN EL TIEMPO, POR ELLO TE BRINDAMOS UNA RESOLUCIÓN DEFINITIVA EN UN LAPSO DE 24 A 48 HORAS HÁBILES.",
      },
      {
        question: "¿CUÁLES SON LOS REQUISITOS PARA CONCRETAR EL TRÁMITE?",
        answer: `TODA LA INFORMACIÓN OBLIGATORIA SE ENCUENTRA DISPONIBLE EN EL <a href="/files/REQUISITOS.pdf" target="_blank" rel="noopener noreferrer" class="${faqLink}">APARTADO DE NUESTRA WEB</a>. EN CASO DE INQUIETUDES, NUESTROS ASESORES TE BRINDAN TODA LA INFORMACIÓN NECESARIA PARA EVALUAR CADA SITUACIÓN DE FORMA PERSONALIZADA.`,
      },
    ],
  },
];

export const OG = {
  locale: "es_AR",
  type: "website",
  url: SITE.url,
  title: `${SITE.title}`,
  description:
    "Sinergia Valores Sistema de fianzas de alquiler 100 % digital con calificacion en 24 hs.",
  image: ogImageSrc,
};
